### ISSUE TITLE
Failed to connect to database: Error

### ISSUE THREAD

**Issue by kalenkovich** [langcog/wordbankr#34]
Hi! I have a problem connecting to the server:

```r
get_instruments()
```

```
Failed to connect to database: Error: Can't connect to server on 'wordbank2-prod.canyiscnpddk.us-west-2.rds.amazonaws.com' (60)
NULL
```

Ping requests to that address time out too. Do you know what I might be doing wrong?

<details>
  <summary>packageVersion('wordbankr')</summary>

```
[1] ‘1.0.0’
```  
</details>

<details>
  <summary>R.version</summary>

```
               _                           
platform       aarch64-apple-darwin20      
arch           aarch64                     
os             darwin20                    
system         aarch64, darwin20           
status                                     
major          4                           
minor          2.1                         
year           2022                        
month          06                          
day            23                          
svn rev        82513                       
language       R                           
version.string R version 4.2.1 (2022-06-23)
nickname       Funny-Looking Kid 
```  
</details>

**Comment by kalenkovich** [comment]
I get this error with both the GitHub and the CRAN versions.

**Comment by mcfrank** [comment]
Sorry about that, server issue. Should be fixed now - let us know?

Mike

**Comment by kalenkovich** [comment]
I still get the same error but now only on my work computer. A couple of colleagues tested it too and had no problems. Must be something specific to my computer :shrug: Thank you for checking!
